/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_a3;

import java.sql.SQLException;
import login.controller.LoginController;

/**
 *
 * @author User
 */
public class Questão_6 extends javax.swing.JFrame {
    private LoginController loginController;
    private int id_Usuario;

    /**
     * Creates new form Questão_6
     */
    public Questão_6(int idUsuario) {
        initComponents();
        this.loginController = new LoginController();
        this.id_Usuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botão3_zs1 = new javax.swing.JRadioButton();
        Botão1_zn = new javax.swing.JRadioButton();
        botão2_zs = new javax.swing.JRadioButton();
        botão4_zl = new javax.swing.JRadioButton();
        botão5_zo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Em que região de São Paulo você vive atualmente?");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Formulário");
        jLabel4.setIconTextGap(10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Questão 6");

        botão3_zs1.setText("Não moro em São Paulo");
        botão3_zs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão3_zs1ActionPerformed(evt);
            }
        });

        Botão1_zn.setText("Zona Norte");
        Botão1_zn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão1_znActionPerformed(evt);
            }
        });

        botão2_zs.setText("Zona Sul");
        botão2_zs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2_zsActionPerformed(evt);
            }
        });

        botão4_zl.setText("Zona Leste");
        botão4_zl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão4_zlActionPerformed(evt);
            }
        });

        botão5_zo.setText("Zona Oeste");
        botão5_zo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão5_zoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botão3_zs1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botão1_zn)
                            .addComponent(botão2_zs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botão5_zo)
                            .addComponent(botão4_zl))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botão1_zn)
                    .addComponent(botão4_zl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botão2_zs)
                    .addComponent(botão5_zo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botão3_zs1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botão3_zs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão3_zs1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
         try{
            
        // Supondo que o valor 3 representa a resposta para a Questão 6 (Não moro em São Paulo)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 3, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }

        new Questão_7(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão3_zs1ActionPerformed

    private void Botão1_znActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão1_znActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 6 (Zona Norte)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 1, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }


        new Questão_7(id_Usuario).setVisible(true);
    }//GEN-LAST:event_Botão1_znActionPerformed

    private void botão2_zsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2_zsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
         try{
            
        // Supondo que o valor 2 representa a resposta para a Questão 6 (Zona Sul)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 2, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }


        new Questão_7(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão2_zsActionPerformed

    private void botão4_zlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão4_zlActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 4 representa a resposta para a Questão 6 (Zona Leste)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 4, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }


        new Questão_7(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão4_zlActionPerformed

    private void botão5_zoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão5_zoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 5 representa a resposta para a Questão 6 (Zona Oeste)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 5, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }


        new Questão_7(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão5_zoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questão_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questão_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questão_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questão_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Botão1_zn;
    private javax.swing.JRadioButton botão2_zs;
    private javax.swing.JRadioButton botão3_zs1;
    private javax.swing.JRadioButton botão4_zl;
    private javax.swing.JRadioButton botão5_zo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
