
package com.mycompany.projeto_a3;

import java.sql.SQLException;
import login.controller.LoginController;

/**
 *
 * @author User
 */
public class Questão_8 extends javax.swing.JFrame {
    private LoginController loginController;
    private int id_Usuario;

    /**
     * Creates new form questão_8
     */
    public Questão_8(int idUsuario) {
        initComponents();
        this.loginController = new LoginController();
        this.id_Usuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botão3_s = new javax.swing.JRadioButton();
        botão4_r = new javax.swing.JRadioButton();
        botão5_mr = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Botão1_exc = new javax.swing.JRadioButton();
        botão2_mb = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botão3_s.setText("Sem Importância");
        botão3_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão3_sActionPerformed(evt);
            }
        });

        botão4_r.setText("Importante");
        botão4_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão4_rActionPerformed(evt);
            }
        });

        botão5_mr.setText("Pouco Importante");
        botão5_mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão5_mrActionPerformed(evt);
            }
        });

        jLabel3.setText("Quão impactante você considera a educação na vida das pessoas?");

        Botão1_exc.setText("Muito Importante");
        Botão1_exc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão1_excActionPerformed(evt);
            }
        });

        botão2_mb.setText("Neutra");
        botão2_mb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2_mbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Formulário");
        jLabel6.setIconTextGap(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botão1_exc)
                            .addComponent(botão2_mb)
                            .addComponent(botão3_s))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botão5_mr)
                            .addComponent(botão4_r))
                        .addGap(21, 21, 21)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botão1_exc)
                    .addComponent(botão4_r))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botão2_mb)
                    .addComponent(botão5_mr))
                .addGap(18, 18, 18)
                .addComponent(botão3_s)
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botão3_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão3_sActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 3 representa a resposta para a Questão 8 (Sem Importância)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 0, 3);
        
        RespostasUsuario telaRespostas = new RespostasUsuario(id_Usuario);
        
        telaRespostas.setVisible(true);
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_botão3_sActionPerformed

    private void Botão1_excActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão1_excActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 8 (Muito Importante)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 0, 1);
        
        RespostasUsuario telaRespostas = new RespostasUsuario(id_Usuario);
        
        
        telaRespostas.setVisible(true);
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_Botão1_excActionPerformed

    private void botão2_mbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2_mbActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 2 representa a resposta para a Questão 8 (Neutra)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 0, 2);
        
        RespostasUsuario telaRespostas = new RespostasUsuario(id_Usuario);
        
        telaRespostas.setVisible(true);
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_botão2_mbActionPerformed

    private void botão4_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão4_rActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 4 representa a resposta para a Questão 8 (Importante)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 0, 4);
        
        RespostasUsuario telaRespostas = new RespostasUsuario(id_Usuario);
        
        
        telaRespostas.setVisible(true);
       
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_botão4_rActionPerformed

    private void botão5_mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão5_mrActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 5 representa a resposta para a Questão 8 (Pouco Importante)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 0, 5);
        
        RespostasUsuario telaRespostas = new RespostasUsuario(id_Usuario);
        
        
        telaRespostas.setVisible(true);
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_botão5_mrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questão_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questão_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questão_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questão_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Botão1_exc;
    private javax.swing.JRadioButton botão2_mb;
    private javax.swing.JRadioButton botão3_s;
    private javax.swing.JRadioButton botão4_r;
    private javax.swing.JRadioButton botão5_mr;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
