/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_a3;

import java.sql.SQLException;
import login.controller.LoginController;

/**
 *
 * @author User
 */
public class Questão_5 extends javax.swing.JFrame {
    private LoginController loginController;
    private int id_Usuario;

    /**
     * Creates new form Questão_5
     */
    public Questão_5(int idUsuario) {
        initComponents();
        this.loginController = new LoginController();
        this.id_Usuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        botão2_s = new javax.swing.JRadioButton();
        botão3_r = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        botão4_s1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Botão1_exc = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Formulário");
        jLabel4.setIconTextGap(10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botão2_s.setText("2-3 pessoas");
        botão2_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2_sActionPerformed(evt);
            }
        });

        botão3_r.setText("1 pessoa");
        botão3_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão3_rActionPerformed(evt);
            }
        });

        jLabel3.setText("Há pessoas na sua família que concluiram ou estão");

        botão4_s1.setText("4 ou mais pessoas");
        botão4_s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão4_s1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Questão 5");

        Botão1_exc.setText("Nenhuma");
        Botão1_exc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão1_excActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Formulário");
        jLabel6.setIconTextGap(10);

        jLabel7.setText("cursando o ensino superior?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botão1_exc)
                            .addComponent(botão2_s))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botão4_s1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botão3_r)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botão1_exc)
                    .addComponent(botão3_r))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botão2_s)
                    .addComponent(botão4_s1))
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botão2_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2_sActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            // Supondo que o valor 2 representa a resposta para a Questão 5 (2-3 pessoas)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 2, 0, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
        

        new Questão_6(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão2_sActionPerformed

    private void botão3_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão3_rActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            // Supondo que o valor 3 representa a resposta para a Questão 5 (1 pessoa)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 3, 0, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }

        new Questão_6(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão3_rActionPerformed

    private void botão4_s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão4_s1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
             // Supondo que o valor 4 representa a resposta para a Questão 5 (4 ou mais pessoas)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 4, 0, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
         
        new Questão_6(id_Usuario).setVisible(true);
    }//GEN-LAST:event_botão4_s1ActionPerformed

    private void Botão1_excActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão1_excActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 5 (Nenhuma)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 1, 0, 0, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }

       new Questão_6(id_Usuario).setVisible(true);
    }//GEN-LAST:event_Botão1_excActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questão_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questão_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questão_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questão_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Botão1_exc;
    private javax.swing.JRadioButton botão2_s;
    private javax.swing.JRadioButton botão3_r;
    private javax.swing.JRadioButton botão4_s1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
