/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_a3;

import java.sql.SQLException;
import login.controller.LoginController;

/**
 *
 * @author User
 */
public class Questão_7 extends javax.swing.JFrame {
    
    private LoginController loginController;
    private int id_Usuario;

    /**
     * Creates new form Questão_7
     */
    public Questão_7(int idUsuario) {
        initComponents();
        this.loginController = new LoginController();
        
        this.id_Usuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botão1_efi = new javax.swing.JRadioButton();
        botão2_efc = new javax.swing.JRadioButton();
        botão4 = new javax.swing.JRadioButton();
        botão3_esc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botão1_efi.setText("Apenas instituições privadas");
        Botão1_efi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão1_efiActionPerformed(evt);
            }
        });

        botão2_efc.setText("Sou/já fui bolsista");
        botão2_efc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2_efcActionPerformed(evt);
            }
        });

        botão4.setText("Apenas instituições públicas");
        botão4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão4ActionPerformed(evt);
            }
        });

        botão3_esc.setText("Já estudei tanto em instituição privada quanto em pública");
        botão3_esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão3_escActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Formulário");
        jLabel2.setIconTextGap(10);

        jLabel3.setText("Você já estudou em instituições de ensino privadas?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Questão 7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botão1_efi)
                                    .addComponent(botão2_efc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botão4))
                            .addComponent(botão3_esc))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botão1_efi)
                    .addComponent(botão4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botão2_efc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botão3_esc)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Botão1_efiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão1_efiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 7 (Apenas instituições privadas)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 1, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }

        
        new Questão_8(id_Usuario).setVisible(true);
        
    }//GEN-LAST:event_Botão1_efiActionPerformed

    private void botão4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 7 (Apenas instituições públicas)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 4, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
        
                new Questão_8(id_Usuario).setVisible(true);
        
    }//GEN-LAST:event_botão4ActionPerformed

    private void botão2_efcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2_efcActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        try{
            
        // Supondo que o valor 1 representa a resposta para a Questão 7 (Sou/já fui bolsista)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 2, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }

        
                new Questão_8(id_Usuario).setVisible(true);
        
    }//GEN-LAST:event_botão2_efcActionPerformed

    private void botão3_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão3_escActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
          try{
            
        // Supondo que o valor 3 representa a resposta para a Questão 7 (Já estudei tanto em instituição privada quanto em pública)
        loginController.respostaFormulario(id_Usuario, 0, 0, 0, 0, 0, 0, 3, 0);
    } catch (SQLException ex) {
        ex.printStackTrace();
        }
        
        
              new Questão_8(id_Usuario).setVisible(true);
        
    }//GEN-LAST:event_botão3_escActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questão_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questão_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questão_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questão_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Botão1_efi;
    private javax.swing.JRadioButton botão2_efc;
    private javax.swing.JRadioButton botão3_esc;
    private javax.swing.JRadioButton botão4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
